name: MDAuth
version: ${project.version}
main: xyz.liamsho.mdauth.MDAuth
api-version: 1.17
load: POSTWORLD
authors: [ LiamSho ]
description: MDAuth for Hecatia Minecraft Server
depend:
  - LuckPerms

commands:
  account:
    usage: "/account <bind|login|reg> <arg1> <arg2> ..."
    description: "Common user commands, used for binding account, etc."

